[package]
name = "q2prog"
version = "0.1.0"
authors = ["Joe Wingbermuehle <joewing@joewing.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.4"
clap = "~2.27.0"
